<?php

namespace Database\Seeders;

use App\Models\Cafe;
use App\Models\FotoCafe;
use App\Models\Fasilitas;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CafeSeeder extends Seeder
{
    public function run(): void
    {
        $cafes = [
            [
                'name' => 'Roaster and Bear',
                'kemantren' => 'Jetis',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Cafe modern dengan interior estetik bernuansa beruang. Tempat yang nyaman dengan sofa empuk, menyajikan hidangan ala Western yang premium, serta sangat kondusif untuk work-from-cafe.',
                'address' => 'Jl. Margo Utomo No.52, Gowongan, Kec. Jetis, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Roaster+and+Bear+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 65000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor', 'AC', 'Sofa', 'Western', 'Estetik', 'Premium', 'Work-from-cafe'],
            ],
            [
                'name' => 'Loko Cafe Malioboro',
                'kemantren' => 'Gedongtengen',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Terletak strategis di kawasan Stasiun Tugu, cafe ini menawarkan tempat transit yang nyaman dengan live music di area outdoor, menyajikan menu tradisional berharga terjangkau dengan view langsung ke jalan Malioboro.',
                'address' => 'Jl. Pasar Kembang No.3a, Sosromenduran, Gedongtengen, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Loko+Cafe+Malioboro+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '23:00',
                'avg_price' => 25000,
                'rating' => 4.4,
                'fasilitas' => ['Outdoor', 'Live Music', 'Transit', 'Malioboro View', 'Traditional', 'Affordable'],
            ],
            [
                'name' => 'Lecker Rumah Kopi',
                'kemantren' => 'Danurejan',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Rumah kopi bergaya vintage heritage dengan perpaduan area indoor dan outdoor yang seimbang. Suasananya tenang dan fokus menyajikan aneka olahan kopi pilihan berkualitas tinggi.',
                'address' => 'Jl. Tukangan No.19, Lempuyangan, Danurejan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Lecker+Rumah+Kopi+Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 30000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Vintage', 'Heritage', 'Calm', 'Coffee-focused'],
            ],
            [
                'name' => 'Kala Jumpa',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Tempat nongkrong minimalis yang luas dengan area ber-AC di dalam maupun luar ruangan. Sangat cocok bagi mahasiswa untuk berkumpul, belajar kelompok, maupun bersantai.',
                'address' => 'Jl. Kartini No.5, Terban, Gondokusuman, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kala+Jumpa+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '23:00',
                'avg_price' => 28000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Minimalis', 'AC', 'Spacious', 'Student-friendly'],
            ],
            [
                'name' => 'Luxury Bench',
                'kemantren' => 'Gondomanan',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Cafe premium berkonsep modern di pusat kota. Menawarkan kenyamanan indoor ber-AC penuh, ruang pertemuan khusus (meeting room), serta layanan eksklusif kelas atas.',
                'address' => 'Jl. Mayor Suryotomo No.25, Ngupasan, Gondomanan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Luxury+Bench+Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 70000,
                'rating' => 4.7,
                'fasilitas' => ['Indoor', 'Modern', 'AC', 'Premium', 'Meeting-room', 'Pusat-Kota'],
            ],
            [
                'name' => 'Civet Coffee Malioboro',
                'kemantren' => 'Pakualaman',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Cafe bernuansa klasik/heritage dekat Malioboro. Menyajikan kopi luwak tradisional asli di ruangan vintage ber-AC yang tenang dan damai, cocok untuk bersantai.',
                'address' => 'Jl. Bausasran No.12, Purwokinanti, Pakualaman, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Civet+Coffee+Malioboro+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 45000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor', 'Vintage', 'Calm', 'Traditional', 'AC', 'Heritage'],
            ],
            [
                'name' => 'Bale Raos',
                'kemantren' => 'Kraton',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Menyajikan kuliner kegemaran para Sultan Yogyakarta dengan nuansa Kraton-vibes yang kental. Area makan dominan outdoor tradisional Jawa yang premium dan berbudaya tinggi.',
                'address' => 'Jl. Magangan Kulon No.1, Panembahan, Kraton, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Bale+Raos+Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '22:00',
                'avg_price' => 85000,
                'rating' => 4.6,
                'fasilitas' => ['Outdoor', 'Javanese', 'Heritage', 'Kraton-vibes', 'Culture', 'Premium'],
            ],
            [
                'name' => 'Kala Kopi',
                'kemantren' => 'Ngampilan',
                'konsep_utama' => 'Minimalis Indoor',
                'description' => 'Cafe mungil (compact) ber-AC di kawasan Ngampilan yang menyajikan kopi lezat dan terjangkau. Pilihan tepat untuk singgah sejenak (quick stop) atau membawa kopi pergi (takeaway).',
                'address' => 'Jl. KH. Ahmad Dahlan No.89, Notoprajan, Ngampilan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kala+Kopi+Ngampilan+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '21:00',
                'avg_price' => 18000,
                'rating' => 4.2,
                'fasilitas' => ['Indoor', 'Compact', 'AC', 'Affordable', 'Quick-stop'],
            ],
            [
                'name' => 'ViaVia Cafe',
                'kemantren' => 'Mantrijeron',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Cafe berkonsep ramah lingkungan di Prawirotaman yang menjadi favorit wisatawan asing. Menyajikan menu artisan organik bergaya Western dan lokal dengan perpaduan area indoor-outdoor yang seimbang.',
                'address' => 'Jl. Prawirotaman No.30, Brontokusuman, Mantrijeron, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=ViaVia+Cafe+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '23:00',
                'avg_price' => 45000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Artisan', 'Western', 'Tourist-friendly', 'Eco-friendly'],
            ],
            [
                'name' => 'Warung Lawas',
                'kemantren' => 'Mergangsan',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Tempat nongkrong dengan gaya pedesaan/rustic yang santai dan terbuka. Menyediakan area sosial semi-outdoor bernuansa vintage dengan harga menu yang sangat merakyat.',
                'address' => 'Jl. Prawirotaman II No.613, Brontokusuman, Mergangsan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Warung+Lawas+Yogyakarta',
                'open_time' => '07:00',
                'close_time' => '22:00',
                'avg_price' => 22000,
                'rating' => 4.3,
                'fasilitas' => ['Outdoor', 'Vintage', 'Affordable', 'Social-space', 'Rustic'],
            ],
            [
                'name' => 'Jiwa Jawi',
                'kemantren' => 'Kotagede',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Cafe tersembunyi berkonsep taman rimbun dengan nuansa tradisional Jawa di daerah bersejarah Kotagede. Tempat yang tenang untuk melarikan diri dari hiruk-pikuk kota.',
                'address' => 'Jl. Tegal Gendu No.14, Prenggan, Kotagede, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Jiwa+Jawi+Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '22:00',
                'avg_price' => 40000,
                'rating' => 4.7,
                'fasilitas' => ['Outdoor', 'Garden', 'Rimbun', 'Heritage', 'Calm', 'Traditional'],
            ],
            [
                'name' => 'Sinergi Coworking Space',
                'kemantren' => 'Umbulharjo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Coworking space dan cafe terintegrasi yang sangat luas, buka 24 jam. Menyediakan fasilitas belajar dan kerja yang nyaman bagi mahasiswa dan pekerja kreatif di daerah Umbulharjo.',
                'address' => 'Jl. Veteran No.150, Pandeyan, Umbulharjo, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Sinergi+Coworking+Space+Yogyakarta',
                'open_time' => '00:00',
                'close_time' => '23:59',
                'avg_price' => 30000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Co-working', 'Student-friendly', '24-Hours', 'Spacious'],
            ],
            [
                'name' => 'Selasar Malioboro Cafe',
                'kemantren' => 'Wirobrajan',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Cafe kasual semi-outdoor dengan hiburan live music yang hangat. Tempat nongkrong asyik bersama teman-teman dengan harga makanan dan minuman yang bersahabat di kantong.',
                'address' => 'Jl. Hos Cokroaminoto No.42, Pakuncen, Wirobrajan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Selasar+Malioboro+Cafe+Yogyakarta',
                'open_time' => '15:00',
                'close_time' => '23:00',
                'avg_price' => 20000,
                'rating' => 4.2,
                'fasilitas' => ['Outdoor', 'Live Music', 'Affordable', 'Social-space', 'Casual'],
            ],
            [
                'name' => 'Artemis Coffee & Space',
                'kemantren' => 'Tegalrejo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Cafe minimalis bergaya industrial dengan kombinasi area indoor ber-AC dan outdoor luas. Suasana produktif menjadikannya favorit pelajar untuk belajar dan berdiskusi.',
                'address' => 'Jl. Kyai Mojo No.78, Bener, Tegalrejo, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Artemis+Coffee+Space+Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '23:00',
                'avg_price' => 25000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor', 'Outdoor', 'Minimalis', 'Industrial', 'Student-friendly', 'AC'],
            ],
            [
                'name' => 'LeGatito Cafe & Playground',
                'kemantren' => 'Jetis',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Cafe keluarga modern dan estetik yang ramah hewan peliharaan (pet-friendly). Dilengkapi fasilitas bermain dan ruangan indoor ber-AC dingin yang menyenangkan untuk anak-anak.',
                'address' => 'Jl. AM. Sangaji No.45, Cokrodiningratan, Jetis, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=LeGatito+Cafe+Playground+Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '21:00',
                'avg_price' => 40000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor', 'AC', 'Pet-friendly', 'Estetik', 'Family-friendly', 'Modern'],
            ],
            [
                'name' => 'Kedai Kopi Mataram',
                'kemantren' => 'Gedongtengen',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kedai kopi vintage di dekat Stasiun Lempuyangan dan Malioboro. Tempat transit yang strategis dan nyaman untuk menikmati kopi hitam klasik dengan harga murah meriah.',
                'address' => 'Jl. Mataram No.55, Suryatmajan, Gedongtengen, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kedai+Kopi+Mataram+Yogyakarta',
                'open_time' => '07:00',
                'close_time' => '22:00',
                'avg_price' => 15000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor', 'Outdoor', 'Vintage', 'Affordable', 'Transit', 'Pusat-Kota'],
            ],
            [
                'name' => 'Dua Coffee Malioboro',
                'kemantren' => 'Danurejan',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Cabang Jakarta yang hadir di pusat Jogja dengan konsep minimalis modern. Pilihan utama untuk work-from-cafe yang didukung WiFi cepat, colokan melimpah, dan AC sejuk.',
                'address' => 'Jl. Abu Bakar Ali No.18, Kotabaru, Danurejan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Dua+Coffee+Malioboro+Yogyakarta',
                'open_time' => '07:00',
                'close_time' => '22:00',
                'avg_price' => 45000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor', 'AC', 'Minimalis', 'Modern', 'Premium', 'Work-from-cafe'],
            ],
            [
                'name' => 'Metropole Coffee',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Cafe berkonsep estetika serba putih (white-aesthetic) di gedung kolonial kuno (heritage). Menyuguhkan suasana premium berkelas tinggi dengan pilihan hidangan lezat.',
                'address' => 'Jl. Sudirman No.21, Kotabaru, Gondokusuman, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Metropole+Coffee+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '23:00',
                'avg_price' => 50000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor', 'Outdoor', 'Heritage', 'Estetik', 'Premium', 'White-aesthetic'],
            ],
            [
                'name' => 'Estuary Cafe',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Cafe bertingkat berdesain industrial modern yang megah dan sangat lapang. Menyediakan ruang kerja yang kondusif dengan sirkulasi udara baik dan pencahayaan estetik.',
                'address' => 'Jl. Monumen Jogja Kembali No.22, Terban, Gondokusuman, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Estuary+Cafe+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '23:00',
                'avg_price' => 38000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Industrial', 'Spacious', 'AC', 'Work-from-cafe'],
            ],
            [
                'name' => 'Kopi Kebon',
                'kemantren' => 'Gondomanan',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Kebun kopi tersembunyi (hidden-gem) di dekat pusat kota. Memberikan nuansa tradisional pedesaan yang tenang berhias pepohonan rindang untuk bersantai dari kesibukan kota.',
                'address' => 'Jl. Brigjen Katamso No.112, Keparakan, Gondomanan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kopi+Kebon+Gondomanan+Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '22:00',
                'avg_price' => 20000,
                'rating' => 4.4,
                'fasilitas' => ['Outdoor', 'Garden', 'Rimbun', 'Calm', 'Traditional', 'Hidden-gem'],
            ],
            [
                'name' => 'Gramika Space',
                'kemantren' => 'Pakualaman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Ruang kreatif pemuda berdesain industrial minimalis. Memadukan kenyamanan indoor ber-AC dan kesegaran outdoor dengan harga ramah kantong mahasiswa.',
                'address' => 'Jl. Jagalan No.34, Purwokinanti, Pakualaman, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Gramika+Space+Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '23:00',
                'avg_price' => 22000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor', 'Outdoor', 'Minimalis', 'Industrial', 'Student-friendly', 'Affordable'],
            ],
            [
                'name' => 'Sujiwa Coffee',
                'kemantren' => 'Kraton',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Cafe berarsitektur tradisional Jawa kolonial dekat Kraton. Suasananya damai dan vintage dengan alunan musik gamelan lembut yang menenangkan pikiran.',
                'address' => 'Jl. Rotowijayan No.15, Kadipaten, Kraton, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Sujiwa+Coffee+Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '21:00',
                'avg_price' => 28000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Javanese', 'Heritage', 'Calm', 'Vintage'],
            ],
            [
                'name' => 'Kopi Pojok Tamansari',
                'kemantren' => 'Ngampilan',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Terletak di sudut destinasi bersejarah Tamansari, menyajikan kopi dan minuman penyegar dahaga yang murah meriah serta sangat ramah bagi wisatawan lokal maupun mancanegara.',
                'address' => 'Jl. Taman No.2, Patehan, Ngampilan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kopi+Pojok+Tamansari+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '18:00',
                'avg_price' => 15000,
                'rating' => 4.3,
                'fasilitas' => ['Outdoor', 'Heritage', 'Tourist-friendly', 'Affordable', 'Casual'],
            ],
            [
                'name' => 'Tujuan Cafe',
                'kemantren' => 'Mantrijeron',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Cafe bergaya retro eklektik dengan ornamen jadul yang estetik dan instagenic. Tempat yang sangat nyaman (cozy) bagi pelancong di area turis Prawirotaman.',
                'address' => 'Jl. Tirtodipuran No.22, Mantrijeron, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Tujuan+Cafe+Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 35000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Estetik', 'Retro', 'Cozy', 'Tourist-friendly'],
            ],
            [
                'name' => 'Kala di Atas (Rooftop)',
                'kemantren' => 'Mantrijeron',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Menyajikan keindahan pemandangan kota dari rooftop yang berdesain modern. Pilihan terbaik untuk nongkrong malam hari sambil menikmati pertunjukan live music akustik.',
                'address' => 'Jl. Prawirotaman I No.40, Mantrijeron, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kala+di+Atas+Rooftop+Yogyakarta',
                'open_time' => '16:00',
                'close_time' => '00:00',
                'avg_price' => 40000,
                'rating' => 4.6,
                'fasilitas' => ['Outdoor', 'Rooftop', 'City-view', 'Live Music', 'Social-space', 'Modern'],
            ],
            [
                'name' => 'Awor Coffee',
                'kemantren' => 'Mergangsan',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Coffee shop legendaris bagi para pencinta kopi Yogyakarta. Buka hingga larut malam (midnight-open), ber-AC dingin, dan berfokus menyajikan racikan espresso premium.',
                'address' => 'Jl. Kolonel Sugiyono No.33, Brontokusuman, Mergangsan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Awor+Coffee+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '02:00',
                'avg_price' => 26000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'AC', 'Compact', 'Student-friendly', 'Midnight-open', 'Coffee-focused'],
            ],
            [
                'name' => 'Sore Sore Coffee',
                'kemantren' => 'Kotagede',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Nikmati keindahan sunset dengan suasana kasual di area kebun outdoor yang luas. Menu kopi susu kekinian yang manis dan murah menjadikannya primadona sore hari.',
                'address' => 'Jl. Kemasan No.52, Purbayan, Kotagede, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Sore+Sore+Coffee+Yogyakarta',
                'open_time' => '15:00',
                'close_time' => '22:00',
                'avg_price' => 18000,
                'rating' => 4.4,
                'fasilitas' => ['Outdoor', 'Garden', 'Sunset-view', 'Relaxed', 'Affordable', 'Casual'],
            ],
            [
                'name' => 'Couvee (Ahmad Dahlan)',
                'kemantren' => 'Wirobrajan',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Terkenal dengan signature kopi susu rasa karamel dan pandan yang lezat. Desain tempat minimalis modern ber-AC yang nyaman untuk singgah sejenak memesan kopi.',
                'address' => 'Jl. KH. Ahmad Dahlan No.66, Notoprajan, Wirobrajan, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Couvee+Ahmad+Dahlan+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 28000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor', 'AC', 'Minimalis', 'Modern', 'Quick-stop', 'Coffee-focused'],
            ],
            [
                'name' => 'Eplus Co-working & Cafe',
                'kemantren' => 'Umbulharjo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Co-working cafe yang lengkap dengan ruang meeting ber-AC dan jaringan internet berkecepatan tinggi. Tempat favorit para mahasiswa untuk mengerjakan tugas dengan produktif.',
                'address' => 'Jl. Glagahsari No.88, Warungboto, Umbulharjo, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Eplus+Co-working+Cafe+Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '23:00',
                'avg_price' => 25000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor', 'Outdoor', 'Co-working', 'Student-friendly', 'Meeting-room', 'AC'],
            ],
            [
                'name' => 'Nuri Coffee & Eatery',
                'kemantren' => 'Tegalrejo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Cafe dan restoran berkonsep modern yang sangat lapang. Menyajikan aneka menu nusantara dan Western yang lezat untuk santap bersama keluarga besar sembari dihibur live music.',
                'address' => 'Jl. Kyai Mojo No.102, Bener, Tegalrejo, Kota Yogyakarta',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Nuri+Coffee+Eatery+Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '22:00',
                'avg_price' => 35000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Spacious', 'Family-friendly', 'Modern', 'Live Music'],
            ],
        ];

        $fasilitasMap = Fasilitas::all()->keyBy('slug');

        foreach ($cafes as $cafeData) {
            $staticFasilitasSlugs = $cafeData['fasilitas'];
            unset($cafeData['fasilitas']);

            $cafeData['slug'] = Str::slug($cafeData['name']);

            $cafe = Cafe::updateOrCreate(
                ['slug' => $cafeData['slug']],
                $cafeData
            );

            $dynamicFasilitasIds = [];
            foreach ($staticFasilitasSlugs as $slugName) {
                $slug = Str::slug($slugName);
                if (isset($fasilitasMap[$slug])) {
                    $dynamicFasilitasIds[] = $fasilitasMap[$slug]->id;
                }
            }

            $cafe->fasilitas()->sync($dynamicFasilitasIds);

            // Buat foto dummy
            FotoCafe::updateOrCreate(
                [
                    'cafe_id' => $cafe->id,
                    'is_primary' => true,
                ],
                [
                    'url' => '/images/cafes/default-' . $cafe->id . '.jpg',
                    'caption' => $cafe->name,
                ]
            );
        }
    }
}
