<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class CafeSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $cafes = [
            [
                'name' => 'Blanco Coffee & Books',
                'kemantren' => 'Jetis',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kafe tenang bernuansa perpustakaan mini yang sangat kondusif untuk membaca buku, fokus bekerja, atau diskusi rapat kecil.',
                'address' => 'Jl. Kranggan No.30',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Blanco%20Coffee%20%26%20Books%20Jl.%20Kranggan%20No.30%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 25000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor', 'AC', 'Rak Buku', 'Wi-Fi Cepat', 'Stopkontak', 'Meja Kerja'],
            ],
            [
                'name' => 'Loko Cafe Malioboro',
                'kemantren' => 'Gedongtengen',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Kafe strategis persis di area Stasiun Tugu dengan pemandangan hiruk-pikuk Malioboro yang cocok untuk tempat singgah.',
                'address' => 'Jl. Pasar Kembang No.3a',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Loko%20Cafe%20Malioboro%20Jl.%20Pasar%20Kembang%20No.3a%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 20000,
                'rating' => 4.4,
                'fasilitas' => ['Outdoor', 'Semi-Outdoor', 'Live Music', 'Tempat Transit', 'Wi-Fi'],
            ],
            [
                'name' => 'Lecker Rumah Kopi',
                'kemantren' => 'Danurejan',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe berkarakter bangunan kolonial kuno yang menyajikan suasana tenang dan berfokus pada racikan kopi tradisional.',
                'address' => 'Jl. Krasak No.7, Kotabaru',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Lecker%20Rumah%20Kopi%20Jl.%20Krasak%20No.7%2C%20Kotabaru%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '23:00',
                'avg_price' => 50000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Outdoor', 'Nuansa Heritage', 'Smoking Area', 'Wi-Fi'],
            ],
            [
                'name' => 'Kala Jumpa',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe modern minimalis yang memiliki area sangat luas dan ramah untuk kalangan pelajar/mahasiswa.',
                'address' => 'Jl. Gondosuli No.9, Baciro',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kala%20Jumpa%20Jl.%20Gondosuli%20No.9%2C%20Baciro%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '23:00',
                'avg_price' => 50000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor', 'Outdoor', 'AC', 'Ruang Luas', 'Student-Friendly', 'Wi-Fi'],
            ],
            [
                'name' => 'Luxury Bench',
                'kemantren' => 'Gondomanan',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kafe bergaya modern premium di pusat kota yang dilengkapi fasilitas formal untuk kebutuhan rapat.',
                'address' => 'Jl. Brigjen Katamso',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Luxury%20Bench%20Jl.%20Brigjen%20Katamso%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 20000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor', 'AC', 'Ruang Rapat (Meeting Room)', 'Area Parkir'],
            ],
            [
                'name' => 'Civet Coffee Malioboro',
                'kemantren' => 'Pakualaman',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kedai kopi berkonsep lawas dan tenang di tengah pusat kota yang menyajikan kopi pilihan.',
                'address' => 'Jl. Malioboro',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Civet%20Coffee%20Malioboro%20Jl.%20Malioboro%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '00:00',
                'avg_price' => 15000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'AC', 'Nuansa Klasik/Heritage', 'Wi-Fi'],
            ],
            [
                'name' => 'Kopi Opak (Kotabaru Branch)',
                'kemantren' => 'Kraton',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kedai kopi berkonsep minimalis industrial di tengah kota yang memisahkan area tenang ber-AC dan area terbuka berkerikil untuk mengobrol.',
                'address' => 'Kawasan Kotabaru',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kopi%20Opak%20(Kotabaru%20Branch)%20Kawasan%20Kotabaru%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '23:00',
                'avg_price' => 20000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor AC', 'Outdoor Kerikil', 'Wi-Fi', 'Colokan Listrik', 'Muted Vibe'],
            ],
            [
                'name' => 'Kala Kopi',
                'kemantren' => 'Ngampilan',
                'konsep_utama' => 'Minimalis Indoor',
                'description' => 'Kedai kopi berukuran ringkas yang dirancang untuk singgah cepat atau pembelian praktis (take-away).',
                'address' => 'Kawasan Ngampilan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kala%20Kopi%20Kawasan%20Ngampilan%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '22:00',
                'avg_price' => 35000,
                'rating' => 4.7,
                'fasilitas' => ['Indoor', 'AC', 'Area Ringkas', 'Menu Ekonomis'],
            ],
            [
                'name' => 'ViaVia Cafe',
                'kemantren' => 'Mantrijeron',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe berwawasan lingkungan yang ramah turis asing, menyajikan aneka roti segar dan menu kuliner sehat.',
                'address' => 'Jl. Prawirotaman No.30',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=ViaVia%20Cafe%20Jl.%20Prawirotaman%20No.30%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '23:00',
                'avg_price' => 35000,
                'rating' => 4.2,
                'fasilitas' => ['Indoor', 'Backyard Outdoor', 'Bakery Artisan', 'Eco-Friendly', 'Wi-Fi'],
            ],
            [
                'name' => 'Warung Lawas',
                'kemantren' => 'Mergangsan',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Tempat nongkrong santai dengan konsep interior pedesaan estetik yang menyajikan menu lokal harga terjangkau.',
                'address' => 'Jl. Prawirotaman No.2',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Warung%20Lawas%20Jl.%20Prawirotaman%20No.2%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '22:00',
                'avg_price' => 15000,
                'rating' => 4.6,
                'fasilitas' => ['Outdoor', 'Semi-Outdoor', 'Ruang Sosial', 'Desain Rustic', 'Wi-Fi'],
            ],
            [
                'name' => 'Jiwa Jawi',
                'kemantren' => 'Kotagede',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Kafe berkonsep kebun rimbun yang tersembunyi dengan nuansa tradisional yang damai jauh dari kebisingan.',
                'address' => 'Kawasan Kotagede',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Jiwa%20Jawi%20Kawasan%20Kotagede%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '23:00',
                'avg_price' => 20000,
                'rating' => 4.2,
                'fasilitas' => ['Full Outdoor Garden', 'Halaman Teduh', 'Tenang', 'Tradisional'],
            ],
            [
                'name' => 'Sinergi Coworking Space',
                'kemantren' => 'Umbulharjo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Tempat kerja komunal dan kafe berskala luas yang buka penuh waktu untuk menampung mahasiswa nugas.',
                'address' => 'Jl. Professor DR. Soepomo Sh',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Sinergi%20Coworking%20Space%20Jl.%20Professor%20DR.%20Soepomo%20Sh%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 20000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor AC', 'Outdoor', 'Buka 24 Jam', 'Colokan Banyak', 'Wi-Fi Kencang'],
            ],
            [
                'name' => 'Selasar Malioboro Cafe',
                'kemantren' => 'Wirobrajan',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Ruang santai semi-terbuka dengan suasana kasual yang sering menyajikan pertunjukan musik akustik langsung.',
                'address' => 'Kawasan Wirobrajan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Selasar%20Malioboro%20Cafe%20Kawasan%20Wirobrajan%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '00:00',
                'avg_price' => 35000,
                'rating' => 4.3,
                'fasilitas' => ['Outdoor', 'Panggung Live Music', 'Area Merokok', 'Harga Murah'],
            ],
            [
                'name' => 'Artemis Coffee & Space',
                'kemantren' => 'Tegalrejo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe modern bergaya industrial dengan pembagian area kerja ber-AC dan area nongkrong terbuka yang seimbang.',
                'address' => 'Kawasan Tegalrejo',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Artemis%20Coffee%20%26%20Space%20Kawasan%20Tegalrejo%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 20000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor AC', 'Outdoor', 'Desain Industrial', 'Wi-Fi', 'Student-Friendly'],
            ],
            [
                'name' => 'LeGatito Cafe',
                'kemantren' => 'Jetis',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kafe estetik berkonsep ramah keluarga dan hewan peliharaan yang memiliki tata ruang dalam bergaya modern.',
                'address' => 'Kawasan Jetis',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=LeGatito%20Cafe%20Kawasan%20Jetis%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 15000,
                'rating' => 4.2,
                'fasilitas' => ['Indoor', 'AC', 'Pet-Friendly Playground', 'Sofa', 'Wi-Fi'],
            ],
            [
                'name' => 'Kedai Kopi Mataram',
                'kemantren' => 'Gedongtengen',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kedai kopi bernuansa jadul di pusat kota, sangat pas untuk tempat singgah setelah berjalan dari Malioboro.',
                'address' => 'Jl. Mataram',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kedai%20Kopi%20Mataram%20Jl.%20Mataram%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '00:00',
                'avg_price' => 50000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor', 'Outdoor', 'Nuansa Vintage', 'Tengah Kota', 'Murah'],
            ],
            [
                'name' => 'Dua Coffee Malioboro',
                'kemantren' => 'Danurejan',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kafe berjejaring nasional dengan konsep minimalis modern yang sangat nyaman untuk kerja remote dari kafe.',
                'address' => 'Kawasan Malioboro',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Dua%20Coffee%20Malioboro%20Kawasan%20Malioboro%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '22:00',
                'avg_price' => 50000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Full AC', 'Meja Panjang', 'Wi-Fi Cepat', 'Premium Kopi'],
            ],
            [
                'name' => 'Metropole Coffee',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe premium bernuansa serba putih bersih yang menempati bangunan cagar budaya arsitektur kolonial.',
                'address' => 'Kawasan Kotabaru',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Metropole%20Coffee%20Kawasan%20Kotabaru%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '23:00',
                'avg_price' => 15000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor AC', 'Outdoor', 'White-Aesthetic', 'Cagar Budaya', 'Premium'],
            ],
            [
                'name' => 'Estuary Cafe',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe industrial berlantai dua dengan kaca-kaca besar yang memberikan kesan ruangan sangat lapang dan terang.',
                'address' => 'Jl. Monumen Jogja Kembali',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Estuary%20Cafe%20Jl.%20Monumen%20Jogja%20Kembali%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '22:00',
                'avg_price' => 35000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor Luas', 'Outdoor Terbuka', 'AC', 'Work-from-Cafe', 'Wi-Fi'],
            ],
            [
                'name' => 'Kopi Kebon',
                'kemantren' => 'Gondomanan',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Kafe bertema halaman rumah tersembunyi dengan rerimbunan pohon, cocok untuk mencari ketenangan tengah kota.',
                'address' => 'Kawasan Sayidan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kopi%20Kebon%20Kawasan%20Sayidan%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 35000,
                'rating' => 4.4,
                'fasilitas' => ['Outdoor Taman', 'Rimbun', 'Tenang', 'Hidden-Gem', 'Tradisional'],
            ],
            [
                'name' => 'Gramika Space',
                'kemantren' => 'Pakualaman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Ruang komunal minimalis industrial berbiaya murah yang populer bagi mahasiswa untuk sekadar mengobrol santai.',
                'address' => 'Kawasan Pakualaman',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Gramika%20Space%20Kawasan%20Pakualaman%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '22:00',
                'avg_price' => 25000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor', 'Outdoor', 'Desain Semen Ekspos', 'Harga Pelajar'],
            ],
            [
                'name' => 'Sujiwa Coffee',
                'kemantren' => 'Kraton',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe berkarakter bangunan rumah klasik Jawa Tengah yang sunyi dengan area taman dalam ruangan yang syahdu.',
                'address' => 'Kawasan Kraton',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Sujiwa%20Coffee%20Kawasan%20Kraton%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '00:00',
                'avg_price' => 20000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor Rumah Jawa', 'Outdoor Teduh', 'Klasik', 'Tenang'],
            ],
            [
                'name' => 'Kopi Pojok Tamansari',
                'kemantren' => 'Ngampilan',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Kedai kopi sederhana di sudut gang wisata cagar budaya yang ramah bagi pelancong lokal maupun asing.',
                'address' => 'Kawasan Wisata Tamansari',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kopi%20Pojok%20Tamansari%20Kawasan%20Wisata%20Tamansari%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '22:00',
                'avg_price' => 25000,
                'rating' => 4.6,
                'fasilitas' => ['Semi-Outdoor', 'Teras Terbuka', 'Ramah Turis', 'Santai'],
            ],
            [
                'name' => 'Tujuan Cafe',
                'kemantren' => 'Mantrijeron',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe estetik bertema retro vintage dengan perpaduan interior warna-warni yang sangat ramah foto.',
                'address' => 'Jl. Tirtodipuran No.22',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Tujuan%20Cafe%20Jl.%20Tirtodipuran%20No.22%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '22:00',
                'avg_price' => 50000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor AC', 'Outdoor Belakang', 'Desain Retro', 'Wi-Fi'],
            ],
            [
                'name' => 'Kala di Atas',
                'kemantren' => 'Mantrijeron',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Kafe atap terbuka modern yang menyuguhkan pemandangan lampu-lampu kota Jogja di waktu malam hari.',
                'address' => 'Kawasan Mantrijeron',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kala%20di%20Atas%20Kawasan%20Mantrijeron%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 15000,
                'rating' => 4.3,
                'fasilitas' => ['Rooftop Area', 'City View', 'Panggung Musik', 'Tempat Nongkrong'],
            ],
            [
                'name' => 'Awor Coffee',
                'kemantren' => 'Mergangsan',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kedai kopi padat berfasilitas pendingin ruangan maksimal yang mengutamakan kualitas seduhan kopi hingga larut malam.',
                'address' => 'Kawasan Mergangsan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Awor%20Coffee%20Kawasan%20Mergangsan%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '22:00',
                'avg_price' => 20000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor Compact', 'Full AC', 'Meja Tugas', 'Buka Larut Malam'],
            ],
            [
                'name' => 'Sore Sore Coffee',
                'kemantren' => 'Kotagede',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Kedai kopi santai berlantai batu kerikil yang sangat cocok dikunjungi sore hari untuk berburu pemandangan senja.',
                'address' => 'Kawasan Basen, Kotagede',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Sore%20Sore%20Coffee%20Kawasan%20Basen%2C%20Kotagede%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 15000,
                'rating' => 4.6,
                'fasilitas' => ['Outdoor Area', 'Sunset-View', 'Halaman Kerikil', 'Harga Terjangkau'],
            ],
            [
                'name' => 'Couvee Ahmad Dahlan',
                'kemantren' => 'Wirobrajan',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kafe kopi modern spesialisasi pesanan cepat dengan interior bernuansa minimalis-futuristik.',
                'address' => 'Jl. KH. Ahmad Dahlan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Couvee%20Ahmad%20Dahlan%20Jl.%20KH.%20Ahmad%20Dahlan%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '00:00',
                'avg_price' => 35000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor', 'AC Dingin', 'Meja Bar', 'Minimalis', 'Wi-Fi Kencang'],
            ],
            [
                'name' => 'Eplus Co-working Cafe',
                'kemantren' => 'Umbulharjo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Tempat gabungan antara ruang kerja bersama dan kafe makan yang ramah untuk mahasiswa mengerjakan tugas kelompok.',
                'address' => 'Kawasan Umbulharjo',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Eplus%20Co-working%20Cafe%20Kawasan%20Umbulharjo%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 25000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor AC', 'Outdoor', 'Ruang Rapat', 'Colokan Listrik'],
            ],
            [
                'name' => 'Peacockoffie',
                'kemantren' => 'Tegalrejo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe minimalis fungsional dengan jaringan Wi-Fi stabil yang sangat populer sebagai basis mahasiswa mengerjakan tugas hingga larut malam.',
                'address' => 'Jl. AM. Sangaji No.72',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Peacockoffie%20Jl.%20AM.%20Sangaji%20No.72%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '00:00',
                'avg_price' => 20000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor AC', 'Semi-Outdoor', 'Wi-Fi Stabil', 'Banyak Colokan', 'Buka Malam'],
            ],
            [
                'name' => 'Nox Coffee Boutique',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kafe butik bergaya elegan Spanyol yang menawarkan kopi premium, kue artisan, dan suasana dalam ruangan sangat eksklusif.',
                'address' => 'Jl. Kaliurang No.22',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Nox%20Coffee%20Boutique%20Jl.%20Kaliurang%20No.22%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '00:00',
                'avg_price' => 15000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'Full AC', 'Sofa Premium', 'Meeting Room', 'Wi-Fi'],
            ],
            [
                'name' => 'Kopi nDalem',
                'kemantren' => 'Kraton',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Kedai kopi yang memanfaatkan halaman teras rumah bangsawan cagar budaya, menyajikan nuansa sejarah Jawa asli.',
                'address' => 'Kawasan Jeron Beteng',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kopi%20nDalem%20Kawasan%20Jeron%20Beteng%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '22:00',
                'avg_price' => 50000,
                'rating' => 4.4,
                'fasilitas' => ['Halaman Outdoor', 'Pendopo Jawa', 'Tradisional', 'Tenang', 'Heritage'],
            ],
            [
                'name' => 'Simetri Coffee Roasters',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe berlantai dua dengan halaman rumput luas untuk nongkrong sore serta ruangan dalam berfasilitas meja laptop mumpuni.',
                'address' => 'Jl. Sabirin No.22, Kotabaru',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Simetri%20Coffee%20Roasters%20Jl.%20Sabirin%20No.22%2C%20Kotabaru%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '22:00',
                'avg_price' => 50000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor AC', 'Garden Outdoor', 'Roastery Kopi', 'Meja Kerja Luas'],
            ],
            [
                'name' => 'Space Coffee Roastery',
                'kemantren' => 'Mergangsan',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe minimalis penyangrai kopi mandiri yang menyediakan pilihan biji kopi artisan melimpah bagi para pencinta kopi.',
                'address' => 'Kawasan Mergangsan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Space%20Coffee%20Roastery%20Kawasan%20Mergangsan%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '22:00',
                'avg_price' => 15000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor AC', 'Outdoor Area', 'Specialty Coffee Bar', 'Minimalis'],
            ],
            [
                'name' => 'Le Mindon',
                'kemantren' => 'Mantrijeron',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe bergaya mediterania-klasik dengan teras terbuka hijau yang menyajikan suasana bersantai intim bagi pelancong.',
                'address' => 'Kawasan Tirtodipuran',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Le%20Mindon%20Kawasan%20Tirtodipuran%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '22:00',
                'avg_price' => 35000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor', 'Outdoor Terbuka', 'Desain Retro', 'Sofa', 'Ramah Turis'],
            ],
            [
                'name' => 'Hayati Specialty Coffee',
                'kemantren' => 'Gondokusuman',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kafe berestetika minimalis Jepang modern berwarna dominan putih bersih yang sangat tenang untuk bekerja.',
                'address' => 'Jl. Demangan Baru No.6-7',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Hayati%20Specialty%20Coffee%20Jl.%20Demangan%20Baru%20No.6-7%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '23:00',
                'avg_price' => 25000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor AC', 'White-Aesthetic', 'Wi-Fi Cepat', 'Filter Coffee Bar'],
            ],
            [
                'name' => 'Sugoi Kopi',
                'kemantren' => 'Umbulharjo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kedai kopi bernuansa pop-kultur Jepang dengan menu ramah kantong mahasiswa kampus di sekitarnya.',
                'address' => 'Jl. Glagahsari',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Sugoi%20Kopi%20Jl.%20Glagahsari%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 20000,
                'rating' => 4.2,
                'fasilitas' => ['Indoor AC', 'Outdoor', 'Ornamen Anime/Jepang', 'Harga Pelajar'],
            ],
            [
                'name' => 'English Ivy Coffee',
                'kemantren' => 'Tegalrejo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe bertema taman rumah barat tersembunyi yang menawarkan ketenangan mutlak untuk fokus belajar.',
                'address' => 'Kawasan AM Sangaji',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=English%20Ivy%20Coffee%20Kawasan%20AM%20Sangaji%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '00:00',
                'avg_price' => 25000,
                'rating' => 4.2,
                'fasilitas' => ['Indoor', 'Garden Outdoor', 'Rimbun', 'Sunyi', 'Meja Kerja'],
            ],
            [
                'name' => 'Kopi Opak City Branch',
                'kemantren' => 'Mergangsan',
                'konsep_utama' => 'Dominan Outdoor',
                'description' => 'Cabang area kota yang membawa konsep warung kopi pinggir sungai terbuka ke tengah kota untuk ruang berkumpul kasual.',
                'address' => 'Kawasan Mergangsan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kopi%20Opak%20City%20Branch%20Kawasan%20Mergangsan%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '00:00',
                'avg_price' => 35000,
                'rating' => 4.4,
                'fasilitas' => ['Full Outdoor', 'Area Sosial', 'Ramah Merokok', 'Makanan Lokal'],
            ],
            [
                'name' => 'Seniman Kopi Jogja',
                'kemantren' => 'Danurejan',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Kedai kopi kayu bergaya klasik dekat pusat keramaian stasiun yang cocok untuk mengobrol santai.',
                'address' => 'Kawasan Danurejan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Seniman%20Kopi%20Jogja%20Kawasan%20Danurejan%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '22:00',
                'avg_price' => 15000,
                'rating' => 4.6,
                'fasilitas' => ['Semi-Outdoor', 'Desain Vintage Tradisional', 'Smoking Area'],
            ],
            [
                'name' => 'Tengah Kota Kopi',
                'kemantren' => 'Gondomanan',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kedai kopi modern minimalis tersembunyi di gang tengah kota yang pas untuk istirahat setelah bepergian.',
                'address' => 'Kawasan Malioboro Belakang',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Tengah%20Kota%20Kopi%20Kawasan%20Malioboro%20Belakang%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '00:00',
                'avg_price' => 15000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor AC', 'Outdoor Kecil', 'Minimalis', 'Stopkontak', 'Wi-Fi'],
            ],
            [
                'name' => 'Antek Coffee',
                'kemantren' => 'Wirobrajan',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe berlantai semen ekspos berkonsep industrial ramah kantong yang menjadi andalan tempat kerja kelompok mahasiswa.',
                'address' => 'Kawasan Wirobrajan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Antek%20Coffee%20Kawasan%20Wirobrajan%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '22:00',
                'avg_price' => 15000,
                'rating' => 4.6,
                'fasilitas' => ['Indoor AC', 'Outdoor Semen', 'Industrial', 'Murah', 'Colokan'],
            ],
            [
                'name' => 'Brick Cafe City Spot',
                'kemantren' => 'Jetis',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe berestetika khas eropa klasik/Inggris dengan batu bata merah ekspos yang sangat ramah foto keluarga.',
                'address' => 'Kawasan Jetis Tengah',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Brick%20Cafe%20City%20Spot%20Kawasan%20Jetis%20Tengah%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '00:00',
                'avg_price' => 15000,
                'rating' => 4.7,
                'fasilitas' => ['Indoor Klasik', 'Outdoor Teras', 'Nuansa Vintage Eropa', 'Sofa'],
            ],
            [
                'name' => 'Umar Kopi',
                'kemantren' => 'Ngampilan',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kedai kopi lokal berdesain sederhana yang menyediakan ruang kerja dalam ruangan tenang serta area teras luar yang ramah merokok.',
                'address' => 'Kawasan Serangan',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Umar%20Kopi%20Kawasan%20Serangan%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '23:00',
                'avg_price' => 35000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor', 'Outdoor Teras', 'Student-Friendly', 'Murah', 'Wi-Fi'],
            ],
            [
                'name' => 'Tugu Kopi Jogja',
                'kemantren' => 'Jetis',
                'konsep_utama' => 'Semi-Outdoor',
                'description' => 'Kedai kopi berteras terbuka yang menyuguhkan pemandangan langsung monumen Tugu Yogyakarta di malam hari.',
                'address' => 'Kawasan Simpang Tugu',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Tugu%20Kopi%20Jogja%20Kawasan%20Simpang%20Tugu%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '00:00',
                'avg_price' => 15000,
                'rating' => 4.5,
                'fasilitas' => ['Outdoor Teras', 'Landmark-View', 'Wisatawan-Friendly', 'Tradisional'],
            ],
            [
                'name' => 'Janji Jiwa X Badak',
                'kemantren' => 'Gedongtengen',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kolaborasi gerai kopi modern berkonsep minimalis cepat saji untuk konsumen transit kereta api.',
                'address' => 'Kawasan Stasiun Tugu',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Janji%20Jiwa%20X%20Badak%20Kawasan%20Stasiun%20Tugu%20Yogyakarta',
                'open_time' => '11:00',
                'close_time' => '00:00',
                'avg_price' => 15000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor Compact', 'AC Dingin', 'Kursi Tunggu', 'Wi-Fi', 'Praktis'],
            ],
            [
                'name' => 'Pojok Kahfi',
                'kemantren' => 'Pakualaman',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe kecil yang tenang di sudut jalan kawasan Pakualaman dengan suasana halaman depan rumah yang teduh.',
                'address' => 'Kawasan Purwokinanti',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Pojok%20Kahfi%20Kawasan%20Purwokinanti%20Yogyakarta',
                'open_time' => '10:00',
                'close_time' => '23:00',
                'avg_price' => 25000,
                'rating' => 4.3,
                'fasilitas' => ['Indoor Mini', 'Outdoor Teras', 'Minimalis', 'Tenang', 'Affordable'],
            ],
            [
                'name' => 'Kotagede Heritage Coffee',
                'kemantren' => 'Kotagede',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe arsitektur rumah kuno mataram islam dengan sentuhan pilar kayu kuno dan tembok batu bata tebal.',
                'address' => 'Kawasan Basen',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Kotagede%20Heritage%20Coffee%20Kawasan%20Basen%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '00:00',
                'avg_price' => 35000,
                'rating' => 4.4,
                'fasilitas' => ['Indoor Heritage', 'Outdoor Halaman', 'Vintage Jawa', 'Bersejarah'],
            ],
            [
                'name' => 'Ethikopia Coffee',
                'kemantren' => 'Umbulharjo',
                'konsep_utama' => 'Balanced (In-Out)',
                'description' => 'Kafe berukuran lapang dengan area dalam ber-AC penuh meja tugas serta halaman samping berkerikil untuk nongkrong malam.',
                'address' => 'Kawasan Glagahsari',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Ethikopia%20Coffee%20Kawasan%20Glagahsari%20Yogyakarta',
                'open_time' => '08:00',
                'close_time' => '00:00',
                'avg_price' => 25000,
                'rating' => 4.2,
                'fasilitas' => ['Indoor AC Luas', 'Outdoor Kerikil', 'Coworking Space', 'Wi-Fi'],
            ],
            [
                'name' => 'Republic Cafe',
                'kemantren' => 'Tegalrejo',
                'konsep_utama' => 'Dominan Indoor',
                'description' => 'Kafe berkonsep formal eksekutif yang didedikasikan untuk ruang kerja privat, pertemuan bisnis, atau pengerjaan tugas serius.',
                'address' => 'Kawasan AM Sangaji',
                'gmaps_url' => 'https://www.google.com/maps/search/?api=1&query=Republic%20Cafe%20Kawasan%20AM%20Sangaji%20Yogyakarta',
                'open_time' => '09:00',
                'close_time' => '23:00',
                'avg_price' => 35000,
                'rating' => 4.5,
                'fasilitas' => ['Indoor', 'AC', 'Private Meeting Room', 'Sofa', 'Kursi Kerja Ergonomis'],
            ],
        ];

        $allFasilitas = [];
        $uniqueFasilitasSlugs = [];
        $icons = ['✨', '🌟', '💫', '🌿', '☕', '💡', '🛋️', '🎵'];
        
        foreach ($cafes as $cafe) {
            foreach ($cafe['fasilitas'] as $f) {
                $slug = Str::slug($f);
                if (!isset($uniqueFasilitasSlugs[$slug])) {
                    $uniqueFasilitasSlugs[$slug] = true;
                    $allFasilitas[] = [
                        'name' => $f,
                        'slug' => $slug,
                        'icon' => $icons[strlen($f) % count($icons)],
                        'created_at' => $now,
                        'updated_at' => $now
                    ];
                }
            }
        }
        
        // 1. Bulk insert Fasilitas
        DB::table('fasilitas')->insert($allFasilitas);
        
        // Retrieve them to get IDs
        $fasilitasMap = DB::table('fasilitas')->pluck('id', 'slug')->toArray();
        
        // 2. Prepare Cafes and relations
        $cafeInserts = [];
        foreach ($cafes as $idx => $cafe) {
            $cafeInserts[] = [
                'name' => $cafe['name'],
                'slug' => Str::slug($cafe['name']),
                'kemantren' => $cafe['kemantren'],
                'konsep_utama' => $cafe['konsep_utama'],
                'description' => $cafe['description'],
                'address' => $cafe['address'],
                'gmaps_url' => $cafe['gmaps_url'],
                'open_time' => $cafe['open_time'],
                'close_time' => $cafe['close_time'],
                'avg_price' => $cafe['avg_price'],
                'rating' => $cafe['rating'],
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ];
        }
        
        // Bulk insert cafes
        DB::table('cafes')->insert($cafeInserts);
        $cafeMap = DB::table('cafes')->pluck('id', 'slug')->toArray();
        
        // 3. Prepare Pivot and Photos
        $pivotInserts = [];
        $photoInserts = [];
        
        foreach ($cafes as $idx => $cafe) {
            $slug = Str::slug($cafe['name']);
            $cafeId = $cafeMap[$slug];
            
            // Photos
            $photoInserts[] = [
                'cafe_id' => $cafeId,
                'url' => '/images/cafes/default-' . (($idx % 15) + 1) . '.jpg',
                'caption' => $cafe['name'],
                'is_primary' => true,
                'created_at' => $now,
                'updated_at' => $now
            ];
            
            // Pivot
            foreach ($cafe['fasilitas'] as $f) {
                $fSlug = Str::slug($f);
                if (isset($fasilitasMap[$fSlug])) {
                    $pivotInserts[] = [
                        'cafe_id' => $cafeId,
                        'fasilitas_id' => $fasilitasMap[$fSlug]
                    ];
                }
            }
        }
        
        // Bulk insert pivot and photos
        DB::table('cafe_fasilitas')->insert($pivotInserts);
        DB::table('foto_cafes')->insert($photoInserts);
    }
}